# Generated by Django 4.2.10 on 2025-04-24 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='theme',
            field=models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme'), ('black', 'Black Theme')], default='light', max_length=10),
        ),
    ]
