# Generated by Django 4.2.10 on 2025-04-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_kz', models.CharField(max_length=255)),
                ('word_en', models.CharField(max_length=255)),
                ('pronunciation', models.CharField(blank=True, max_length=255)),
                ('definition', models.TextField()),
                ('example_kz', models.TextField(blank=True)),
                ('example_en', models.TextField(blank=True)),
                ('audio', models.FileField(blank=True, null=True, upload_to='word_audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='words', to='dictionary.category')),
            ],
            options={
                'ordering': ['word_kz'],
            },
        ),
    ]
