# Generated by Django 4.2.10 on 2025-04-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='word',
            name='definition_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='word',
            name='example_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='word',
            name='word_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
