# Generated by Django 4.2.10 on 2025-04-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonlevel',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
