# Generated by Django 4.2.10 on 2025-04-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_lessonlevel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_text_ru',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='content_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lessonlevel',
            name='description_ru',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessonlevel',
            name='name_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_ru',
            field=models.TextField(blank=True),
        ),
    ]
